/*
 * This Kotlin source file was generated by the Gradle "init" task.
 */
package dev.cryztalzone.aurora_prime.app

import org.junit.jupiter.api.Test

import org.junit.jupiter.api.Assertions.assertEquals

class MessageUtilsTest {

}
